export const Actions = {
    NEW_COURSE_ACTION: "NEW_COURSE",
    CREATE_COURSE_SUCCESS_ACTION: "CREATE_COURSE_SUCCESS",
    UPDATE_COURSE_SUCCESS_ACTION: "UPDATE_COURSE_SUCCESS",
    COURSES_LOAD_SUCCESS_ACTION: "COURSES_LOAD_SUCCESS"
};